package start;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chiragparmar' at '24/05/16 10:40 AM' with Gradle 2.9
 *
 * @author chiragparmar, @date 24/05/16 10:40 AM
 */
@Controller
public class Library {
	
	@RequestMapping("/home")
	public String getValue(Model model) {
		return "landing";
	}

}
