

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'chiragparmar' at '24/05/16 10:40 AM' with Gradle 2.9
 *
 * @author chiragparmar, @date 24/05/16 10:40 AM
 */
public class LibraryTest {
	
	
}
